#!/usr/bin/env python3
"""
Assemble the final Slimefun jar, replicating `mvn package` (maven-jar +
maven-shade) semantics:

 1. Slimefun classes (from pass 2, compiled with -source/-target 16) are
    RELOCATED with the same three relocations the maven-shade-plugin performs:
      io.github.bakedlibs.dough     -> io.github.thebusybiscuit.slimefun4.libraries.dough
      io.papermc.lib                -> io.github.thebusybiscuit.slimefun4.libraries.paperlib
      org.apache.commons.lang       -> io.github.thebusybiscuit.slimefun4.libraries.commons.lang
 2. The shaded libraries (dough / paperlib / commons-lang, under their
    relocated names) are merged in as class files.
 3. Filtered resources (plugin.yml gets ${project.version} substituted) plus
    config.yml, item-models.yml, wiki.json, translators.json, tags/*.json,
    biome-maps/*.json, languages/**/*.yml and LICENSE are added.
 4. A minimal MANIFEST and the project's Maven metadata are written.

Env:
  SF    the Slimefun repository (default: /home/user/plugin-slimefun)
  WORK  the build work dir      (default: /tmp/build)

Usage: assemble.py [out.jar]  (default: $WORK/dist/Slimefun v$VERSION.jar)
"""
import os
import sys
import zipfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from relocate import relocate_class  # noqa: E402

SF = os.environ.get("SF", "/home/user/plugin-slimefun")
WORK = os.environ.get("WORK", "/tmp/build")
VERSION = "4.9-UNOFFICIAL"

RELOCATIONS = [
    ("io/github/bakedlibs/dough", "io/github/thebusybiscuit/slimefun4/libraries/dough"),
    ("io/papermc/lib", "io/github/thebusybiscuit/slimefun4/libraries/paperlib"),
    ("org/apache/commons/lang", "io/github/thebusybiscuit/slimefun4/libraries/commons/lang"),
]


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else f"{WORK}/dist/Slimefun v{VERSION}.jar"
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    z = zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED)

    # 1) manifest
    z.writestr("META-INF/MANIFEST.MF", "Manifest-Version: 1.0\r\n")

    # 2) project maven metadata (as maven-jar/shade would embed)
    z.writestr("META-INF/maven/com.github.slimefun/Slimefun/pom.properties",
               "#Generated by local offline build\n"
               f"version={VERSION}\ngroupId=com.github.slimefun\nartifactId=Slimefun\n")
    with open(f"{SF}/pom.xml", "rb") as f:
        z.writestr("META-INF/maven/com.github.slimefun/Slimefun/pom.xml", f.read())

    # 3) Slimefun classes, relocated
    n_classes = 0
    for root, _, files in os.walk(f"{WORK}/classes"):
        for fn in sorted(files):
            if not fn.endswith(".class"):
                continue
            p = os.path.join(root, fn)
            rel = os.path.relpath(p, f"{WORK}/classes")
            data = open(p, "rb").read()
            data = relocate_class(data, RELOCATIONS)
            z.writestr(rel, data)
            n_classes += 1

    # 4) shaded libraries (already relocated, taken from the reference build)
    n_lib = 0
    lib_dir = os.environ.get("RELOCATED_LIBS", f"{SF}/tools/offline-build/lib/relocated")
    for lib in ("dough", "paperlib", "commons"):
        base = f"{lib_dir}/{lib}/io/github/thebusybiscuit/slimefun4/libraries/{lib}"
        for root, _, files in os.walk(base):
            for fn in sorted(files):
                p = os.path.join(root, fn)
                rel = os.path.relpath(p, f"{lib_dir}/{lib}")
                z.writestr(rel, open(p, "rb").read())
                n_lib += 1

    # 5) filtered + copied resources (mirrors the pom <resources> section)
    res = f"{SF}/src/main/resources"
    z.writestr("plugin.yml", open(f"{res}/plugin.yml").read().replace("${project.version}", VERSION))
    for plain in ("config.yml", "item-models.yml", "wiki.json"):
        z.writestr(plain, open(f"{res}/{plain}", "rb").read())
    z.writestr("languages/translators.json", open(f"{res}/languages/translators.json", "rb").read())
    for sub in ("tags", "biome-maps"):
        for root, _, files in os.walk(f"{res}/{sub}"):
            for fn in sorted(files):
                p = os.path.join(root, fn)
                z.writestr(os.path.relpath(p, res), open(p, "rb").read())
    for root, _, files in os.walk(f"{res}/languages"):
        for fn in sorted(files):
            if fn.endswith(".yml"):
                p = os.path.join(root, fn)
                z.writestr(os.path.relpath(p, res), open(p, "rb").read())

    # 6) LICENSE
    z.writestr("LICENSE", open(f"{SF}/LICENSE", "rb").read())

    z.close()
    print(f"assembled {out_path}")
    print(f"  slimefun classes: {n_classes}")
    print(f"  shaded lib classes: {n_lib}")


if __name__ == "__main__":
    main()
